version: "3"
services:
  app:
    ports:
      - "8080:80"
    build: site
    container_name: gamer_apache
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: gamer_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gamer_db
      MYSQL_ROOT_PASSWORD: gamer_password
      MYSQL_USER: gamer_root
      MYSQL_PASSWORD: gamer_password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gamer_phpmyadmin
    depends_on:
      - database
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
