/:
  controller: Main
  action: home

/articles:
  controller: Article
  action: showArticles

/article/:id:
  controller: Article
  action: showOneArticle
  param: id

/article/update/:id:
  controller: Article
  action: updateArticle
  param: id

/article/delete/:id:
  controller: Article
  action: deleteArticle
  param: id

/article/create:
  controller: Article
  action: createArticle

/users:
  controller: User
  action: showUsers

/user/:id:
  controller: User
  action: updateUser
  param: id

/user/check/:verificationCode:
  controller: User
  action: checkUser
  param: verificationCode

/user/delete/:id:
  controller: User
  action: deleteUser
  param: id

/user/create:
  controller: User
  action: createUser

/login:
  controller: User
  action: showLogin

/register:
  controller: User
  action: showRegister

/logout:
  controller: Main
  action: logout

/404:
  controller: Main
  action: page404
