/:
  controller: Main
  action: home

/pages:
  controller: Page
  action: showPages

/pages/create:
  controller: Page
  action: createPage

/page/:url:
  controller: Page
  action: showOnePage
  param: url

/page/edit/:id:
  controller: Page
  action: updatePage
  param: id

/page/delete/:id:
  controller: Page
  action: deletePage
  param: id

/users:
  controller: User
  action: showUsers

/user/:id:
  controller: User
  action: updateUser
  param: id

/user/check/:verificationCode:
  controller: User
  action: checkUser
  param: verificationCode

/user/resetpassword/:verificationCode:
  controller: User
  action: resetPassword
  param: verificationCode

/user/delete/:id:
  controller: User
  action: deleteUser
  param: id

/login:
  controller: User
  action: showLogin

/forgot:
  controller: User
  action: showForgot

/register:
  controller: User
  action: showRegister

/logout:
  controller: User
  action: logout
