/:
  controller: Main
  action: home

/articles:
  controller: Article
  action: showArticles

/article/:id:
  controller: Article
  action: showOneArticle
  param: id

/article/update/:id:
  controller: Article
  action: updateArticle
  param: id

/article/delete/:id:
  controller: Article
  action: deleteArticle
  param: id

/article/create:
  controller: Article
  action: createArticle

/categories:
  controller: Category
  action: showCategories

/category/:name:
  controller: Category
  action: showRelatedArticles
  param: name

/category/update/:name:
  controller: Category
  action: updateCategory
  param: name

/category/delete/:name:
  controller: Category
  action: deleteCategory
  param: name

/category/create:
  controller: Category
  action: createCategory
  param: name

/events:
  controller: Event
  action: showEvents

/event/update/:id:
  controller: Event
  action: updateEvent
  param: id

/event/delete/:id:
  controller: Event
  action: deleteEvent
  param: id

/event/create:
  controller: Event
  action: createEvent
  param: id

/settings:
  controller: Settings
  action: showSettings

/users:
  controller: User
  action: showUsers

/user/:id:
  controller: User
  action: showOneUser
  param: id

/user/update/:id:
  controller: User
  action: updateUser
  param: id

/user/delete/:id:
  controller: User
  action: deleteUser
  param: id

/user/create:
  controller: User
  action: createUser

/login:
  controller: User
  action: showLogin

/register:
  controller: User
  action: showRegister

/logout:
  controller: Main
  action: logout

/404:
  controller: Main
  action: page404
